apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-canvas-packages
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 30Gi
  storageClassName: gcs-fuse-fake #does not need to refer to an existing StorageClass object
  mountOptions:
    - implicit-dirs
    - uid=1001
    - gid=3003
  claimRef:
    namespace: default
    name: gcs-canvas-packages
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: rad-packages-1234 # the gcs bucket
    readOnly: true
