apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-canvas-packages
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  volumeName: gcs-canvas-packages
  storageClassName: gcs-fuse-fake
